Create task
noxiousghost/todo-cli-app pull request #2
Opened 2024-11-08 05:19 UTC by noxiousghost

In this PR I have add a basic feature for creating and saving a new task from cli to the json file. The main changes are as follows:
-[x] Created an interface and enum for tasks status in /interface/tasks.interface.ts file which is used for type checking of a task.
-[x] User can create a new task by running todo-cli add -n "task name" -d "deadline date" -t "tag1" "tag2".. etc. By default, the task is set to todo status and is not archived. Also the program checks for the required directory and json file where task are to be stored and creates if they don't already exist.

2024-11-11 04:52 UTC, arjandhakal commented on src/interface/task.interface.ts
> +export enum taskStatus {
Let's change this to 'TaskStatus'

2024-11-11 04:52 UTC, arjandhakal commented on src/interface/task.interface.ts
> +  inProgress = 'IN PROGRESS',
For constant values, it would be better to have it as `IN_PROGRESS='IN_PROGRESS'`

2024-11-11 04:53 UTC, arjandhakal commented on src/interface/task.interface.ts
> +export interface ITask {
Let's skip the `I` prefix and just keep it as `Task`

2024-11-11 05:12 UTC, arjandhakal commented on src/index.ts
> +    const newTask: Task = {
The callback function can be broken down into more usable functions, such as function to readAndParseJson file , Write a file

2024-11-11 05:14 UTC, arjandhakal commented on src/index.ts
> +    if (!fs.existsSync(dirPath)) {
This seems to be something that needs to be done while CLI tool first starts, and will probably be needed for other commands too. It probably needs to be moved and called in somekind of initial bootstrap method

2024-11-11 05:15 UTC, arjandhakal commented on src/index.ts
> +    const dirPath = path.resolve(__dirname, '../jsons/');
It's better to have both dirPath and filePath as a reusable variable and outside this funciton

2024-11-11 05:16 UTC, arjandhakal commented on src/index.ts
> +    fs.readFile(filePath, 'utf-8', (err, data) => {
This callback functions can be changed into something more elegant and readable using util.promisify.

2024-11-13 04:32 UTC, Nijarshrestha commented on eslint.config.mjs
> +      // 'no-unused-vars': [
let's remove this commented out code if not needed.

2024-11-13 04:44 UTC, Nijarshrestha commented on src/controllers/tasks.controller.ts
> +import { Task, TaskStatus } from '../interface/task.type';
Let's use absolute import instead of relative.

2024-11-13 05:13 UTC, noxiousghost commented on src/controllers/tasks.controller.ts
> +import { Task, TaskStatus } from '../interface/task.type';
Can you please clarify this with an example and if you provide a general instructions on how set it up then that would be a great help.

2024-11-13 11:37 UTC, Nijarshrestha commented on src/controllers/tasks.controller.ts
> +import { Task, TaskStatus } from '../interface/task.type';
Yes, We can configure `tsconfig.json` file by adding 

```{
    "compilerOptions": {
      "baseUrl": "./",
      "paths": {
         "@src/*": ["src/*"],
         "@utils/*": ["src/utils/*"]
      }
   }
   
  The @src and @utils prefix are just examples and can be customized according to your project's needs.
  ```
  This should then make imports as absolute meaning without any trailing forward slashes.
  
  `'../interface/task.type';` => `@src/interface/task.type`

2024-11-13 13:30 UTC, rrojan requested changes

2024-11-13 13:30 UTC, rrojan commented on src/utils/checkFile.ts
> +    fs.writeFileSync(filePath, JSON.stringify([]));
Avoid sync functions like the plague

2024-11-13 13:31 UTC, rrojan commented on src/utils/checkFile.ts
> +    fs.writeFileSync(filePath, JSON.stringify([]));
In Node.js, any synchronous operation will block the main event loop until it completes.

Practically speaking it doesn't really matter for a CLI tool, but for web servers, services, etc sync functions will block the main thread and all requests will have to wait for a sync function to process before being handled.

2024-11-13 13:36 UTC, rrojan commented on src/utils/checkFile.ts
> +    fs.writeFileSync(filePath, JSON.stringify([]));
https://nodejs.org/en/learn/asynchronous-work/overview-of-blocking-vs-non-blocking

2024-11-14 11:20 UTC, noxiousghost commented on src/utils/checkFile.ts
> +    fs.writeFileSync(filePath, JSON.stringify([]));
I made the mkdir and writeFile method asynchronous however, I couldn't make the existsSync method asynchronous. I checked for it's alternative method i.e. fs.exists() but found it is Deprecated as seen in the [official nodejs dos](https://nodejs.org/api/fs.html#fsexistspath-callback). It also suggested to use fs.access() method instead. The thing with fs.access() method is that it doesn't return any thing unlike fs.existsSync() which returns boolean and it was easier to check for file or folder using if statements. I tried to implement fs.access() method in try..catch block as:
``` 
const mkdir = util.promisify(fs.mkdir);
const writeFile = util.promisify(fs.writeFile);
const access = util.promisify(fs.access);

export const dirPath = path.resolve(__dirname, '../jsons/');
export const filePath = path.join(dirPath, '/tasks.json');

export const checkFilePath = async (): Promise<void> => {
try {
    await mkdir(dirPath, { recursive: true });
    try {
      await access(filePath);
    } catch (error) {
      writeFile(filePath, JSON.stringify([]));
    }
  } catch (error) {
    throw error;
  } 
}
```
  

The problem that I'm exprencing with this is that, if there is no tasks.json file in the directory then the program throws an error while trying to add the task. The tasks.json file is indeed created without any entry. Only in the second try (once the file is present in the directory) the tasks are entered. 

This wasn't a problem while using existsSync method to check for file or folder. I haven't committed these changes yet. I need your suggestion in this case.

2024-11-15 02:55 UTC, rrojan commented on src/utils/checkFile.ts
> +    fs.writeFileSync(filePath, JSON.stringify([]));
I think this can be dealt with with proper error handling, and a single recursive retry. Let's look over this today when I come to office.

Also you can make `checkFilePath` return a boolean, just like `fs.existsSync` does:

```ts
import { promises as fs } from 'fs'

const checkFileExists = async (filePath: string): Promise<boolean> => {
  try {
    await fs.access(filePath)
    return true
  } catch (error) {
    return false
  }
}
```

2024-11-15 02:58 UTC, rrojan requested changes

2024-11-15 02:58 UTC, rrojan commented on src/utils/jsonOperations.ts
> +const readFile = util.promisify(fs.readFile);
This is an old way of doing things. Instead fs exports a `promises` submodule that you can use

```ts
import { promises as fs } from 'fs'
...
...
aawait fs.writeFile(...)
```

https://nodejs.org/api/fs.html#promises-api

2024-11-18 05:40 UTC, arjandhakal approved these changes

2024-11-18 05:41 UTC, Nijarshrestha approved these changes

2024-11-18 05:46 UTC, merged