Validation
noxiousghost/todo-cli-app pull request #3
Opened 2024-11-13 11:26 UTC by noxiousghost

This PR is all about validating create task schema using zod. I have done the following changes:
1. Created a dedicate zod schema for validating various elements of create task.
2. Add additional validation for deadline: deadline date should be greater than current date/time
3. Removed previous Task type and TaskStatus enum and used zod schema for type checking where possible.

2024-11-13 11:38 UTC, rrojan requested changes

2024-11-13 11:38 UTC, rrojan commented on src/model/zod.schema.ts
> +});
You can also extract the Task type directly from TaskSchema instead of creating it manually, which has the risk of being out of sync in case we change something in our schema but not our type, and vice versa:

```ts
export type Task = z.infer<typeof TaskSchema>
```

2024-11-13 11:38 UTC, rrojan commented on src/model/zod.schema.ts
> +export const taskSchema = z.object({
CapitalCase is often used for schema vars in zod because it aligns with naming conventions for classes and types in TypeScript, and schema is practically just a blueprint for validating an object type.

```suggestion
export const TaskSchema = z.object({
```

2024-11-13 11:38 UTC, rrojan commented on src/utils/jsonOperations.ts
> +export const readJsonFile = async (filePath: string): Promise<z.infer<typeof taskSchema>[]> => {
Assign `z.infer` to its own type instead, as shown in a past change request.

2024-11-13 11:38 UTC, rrojan commented on src/controllers/tasks.controller.ts
> +    const newTask: z.infer<typeof taskSchema> = {
Since `z.infer` is used so commonly, extract it to a `Task` type, like shown in a previous change request

2024-11-13 11:38 UTC, rrojan commented on src/controllers/tasks.controller.ts
> +    let tasks = [];
```suggestion
    let tasks: Task[] = [];
```
When you intialize an array without any type, it becomes `any[]`

2024-11-13 12:04 UTC, rrojan approved these changes
LGTM :trophy: 
Great job with this one, and kudos on taking the suggestion and implementing validation accordingly

2024-11-14 04:02 UTC, arjandhakal approved these changes

2024-11-14 06:00 UTC, Nijarshrestha approved these changes

2024-11-18 05:21 UTC, merged