009 ux improvements
noxiousghost/todo-cli-app pull request #9
Opened 2024-11-21 17:21 UTC by noxiousghost

I have added few improvements related to UX in this PR. Here is the overview of this feature:
- [x] Replace output format of all the messages that are displayed in the console with new custom formatted logging methods.

**_I have added an additional package called [Chalk](https://www.npmjs.com/package/chalk/v/4.1.2) which helps for formatting the output._** 

The following are the file changes:
- I renamed the file _displayTasks.ts_ to _displayOutputs.ts_ because I did not want to create an additional file that contains configuration for chalk related methods. displayTasks.ts had a method that simply console logged Tasks in the terminal. I decided to create other methods related to displaying formatted output in the same file and _displayOutputs.ts_  seems to be more generic name than _displayTasks_

- In _displayOutputs.ts_ file, I have added extra methods: error, success, info, warning (all taking message of type string as argument), displayOneTask (taking an object of Task type) and modified the existing displayTasks method (taking an array of Task type as argument) with chalk library properties. I've added colors, font weight and emojis where appropriate. 
- In tasks.controller.ts, I have simply replaced console.log and console.error with relatable log methods which I created in the _displayOutptuts.ts_ file

Here are some of the snaps from the terminal: 
![image](https://github.com/user-attachments/assets/288e4706-88a5-4b3c-8066-b8a333e715dc)

![image](https://github.com/user-attachments/assets/995598ae-28ee-4b44-ac2e-19b3e90bfa84)

> Note: I had tried to display the tasks in tabular format using a package called [cli-table3](https://www.npmjs.com/package/cli-table3). It did work when the terminal was viewed in full screen but when the size of terminal is small then it was a mess, significantly degreading the UX. The whole structure was jumbled making it hard to read. The fact is most of the people don't user terminal in full screen. So I thought of displaying the tasks in a list (as it is now) because this way the content doesn't break with the change in size of terminal window.

2024-11-22 03:45 UTC, rrojan requested changes

2024-11-22 03:45 UTC, rrojan commented on src/utils/displayOutputs.ts
> +  console.log(chalk.blue.bold(`ℹ️ INFO: ${message}`));
It would be better to make this a wrapper class. You can also implement factory pattern for all these `log...` functions to reduce the amount of code you write.

[Factory pattern](https://www.patterns.dev/vanilla/factory-pattern/) has mixed opinions across different people, but this can be a good experience for you to dive into basic design patterns :)

2024-11-22 03:45 UTC, rrojan commented on src/controllers/tasks.controller.ts
> +    }
Are there cases where error won't be an instanceof Error? Iirc all errors that are `throw`n inherit from base Error class in one way or another, so this condition will always be `true`

2024-11-22 03:45 UTC, rrojan commented on src/utils/displayOutputs.ts
> +  console.log(chalk.blue.bold(`ℹ️ INFO: ${message}`));
E.g. usage:
```js
logger.success("I did something!")
logger.error("Oh no!")
```

2024-11-22 04:32 UTC, noxiousghost commented on src/controllers/tasks.controller.ts
> +    }
I don't think there will be any cases when error won't be an instance of Error. I did this as a process of type narrowing as suggested by Arjan. right now, logError accepts a message of type string and error is of type unknown. Passing error in logError simply resulted in type error. 
If there are better alternatives to this approach then please let me know. I will implement it instead.

2024-11-26 06:28 UTC, arjandhakal commented on src/utils/displayOutputs.ts
> +}
const logger = new Logger()

export {logger}

import this logger in other classes.

2024-11-26 06:28 UTC, arjandhakal commented on src/utils/displayOutputs.ts
> +  static error = (message: string): void => {
I don't think we need static here

2024-11-27 04:28 UTC, noxiousghost commented on src/utils/displayOutputs.ts
> +}
done

2024-11-27 04:28 UTC, noxiousghost commented on src/utils/displayOutputs.ts
> +  static error = (message: string): void => {
done

2024-12-30 16:28 UTC, merged